# Generated by Django 4.1.7 on 2023-04-17 00:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concierto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artista", models.CharField(max_length=100)),
                ("nombre_concierto", models.CharField(max_length=100)),
                ("fecha_evento", models.DateTimeField()),
                ("num_tickets_disponibles", models.IntegerField()),
                ("descripcion_artista", models.TextField()),
                ("precio_ticket", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("apellido", models.CharField(max_length=30)),
                ("cedula", models.CharField(max_length=10)),
                ("telefono", models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_compra",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("total_compra", models.FloatField()),
                ("cantidad_tickets", models.IntegerField(default=1)),
                (
                    "concierto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ComprasTickets.concierto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ComprasTickets.usuario",
                    ),
                ),
            ],
        ),
    ]
