# Generated by Django 4.1.7 on 2023-05-28 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComprasTickets', '0002_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='concierto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ComprasTickets.concierto'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ComprasTickets.usuario'),
        ),
    ]
